roles:
    - src: git+https://github.com/RiotKit/ansible-basic-software-role
      version: v1.0.0
    - src: git+https://github.com/RiotKit/ansible-advanced-user-role.git
      version: v1.1
    - src: git+https://github.com/RiotKit/ansible-logs-role.git
      version: v1.0.0
    - src: git+https://github.com/RiotKit/ansible-ssh-fallback-port-role.git
      version: v1.0.0
    - src: git+https://github.com/RiotKit/ansible-basic-security-role.git
      version: v1.0.0
    - src: git+https://github.com/RiotKit/ansible-tweak-role.git
      version: v1.0.0
    - src: git+https://github.com/RiotKit/ansible-partial-disk-encryption-role.git
      version: v1.0.0
    - src: oefenweb.fail2ban
      version: v3.3.14
