#
# PREPARE MACHINES PLAYBOOK
# =========================
#   Prepares a complete setup for each machine - including users, firewall, docker, journald
#


#
# Make sure we still know the port, even when we changed the port for security reasons on previous runs
#
- hosts: all
  gather_facts: no
  roles:
      - role: blackandred.server_ssh_fallback_port
        when: ssh_fallback_port is defined and ssh_fallback_port > 0
        vars:
            fallback_ssh_port: "{{ ssh_fallback_port }}"


#
# Run all roles one-by-one
#
- hosts: all
  gather_facts: yes
  force_handlers: yes
  tasks:
      # ===================================
      # Set misc system settings eg. locale
      # ===================================
      - name: Set system settings
        when: role_system_settings is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_system_settings | combine(role_system_settings | default({}), recursive=True) }}"

          - include_role: name=system-settings
            tags: system_settings

      # ==========
      # Multi User
      # ==========
      - name: Users management role
        when: role_users is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_users | combine(role_users | default({}), recursive=True) }}"

          - include_role: name=blackandred.server_multi_user
            tags: users

      # ==============
      # Basic Software
      # ==============
      - name: Basic Software role
        when: role_basic_software is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_basic_software | combine(role_basic_software | default({}), recursive=True) }}"

          - include_role: name=blackandred.server_basic_software
            tags: basic_software

      # ========
      # Tweaking
      # ========
      - name: Tweaking role
        when: role_tune is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_tune | combine(role_tune | default({}), recursive=True) }}"

          - include_role: name=infrastructure-ansible-tweak-os
            tags: tune

      # ====
      # Logs
      # ====
      - name: Logs role
        when: role_logs is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_logs | combine(role_logs | default({}), recursive=True) }}"

          - include_role: name=infrastructure-ansible-logs
            tags: logs

      - name: Fail2ban role
        when: role_fail2ban is defined
        block:
          - name: Include required vars
            set_fact:
            args: "{{ default_role_fail2ban | combine(role_fail2ban | default({}), recursive=True) }}"

          - name: Touch /var/log/auth.log
            become: yes
            path: /var/log/auth.log
            state: touch

          - include_role: name=oefenweb.fail2ban
            tags: fail2ban
